from turtle import Turtle , Screen
# A = Turtle()
# A.shape("turtle")
# A.color("blue","cyan")
# screen = Screen()
# def move_forward():
#     A.forward(10)
# def move_backward():
#     A.backward(10)
# def move_r():
#     A.right(10)
# def move_l():
#     A.left(10)
# screen.listen()
# screen.onkey(move_forward, "w")
# screen.onkey(move_backward, "s")
# screen.onkey(move_r, "d")
# screen.onkey(move_l, "a")
# screen.exitonclick()
A = Turtle()
A.shape("turtle")
A.color("blue")
B = Turtle()
B.shape("turtle")
B.color("green")
C = Turtle()
C.shape("turtle")
C.color("cyan")
E = Turtle()
E.shape("turtle")
E.color("red")
D = Turtle()
D.shape("turtle")
D.color("purple")
F = Turtle()
F.shape("turtle")
F.color("pink")
screen = Screen()
screen.setup(500,400)
screen.textinput(title="bet on turtle",prompt = "what color you bet on it:")
A.penup()
A.goto(x = -250 , y = -30)
C.penup()
C.goto(x = -250 , y = -60)
D.penup()
D.goto(x = -250 , y = 30)
B.penup()
B.goto(x = -250 , y = 60)
E.penup()
E.goto(x = -250 , y = 90)
F.penup()
F.goto(x = -250 , y = 0)
screen.exitonclick()